import AsyncStorage from '@react-native-async-storage/async-storage';
import { createContext, useContext, useEffect, useMemo, useState, type ReactNode } from 'react';

export type AppLanguage = 'en' | 'es';

const LANGUAGE_STORAGE_KEY = 'faithandme.language.v1';

const en = {
  'tabs.today': 'Today',
  'tabs.bible': 'Bible',
  'tabs.ask': 'Ask',
  'tabs.journal': 'Journal',
  'tabs.me': 'Me',

  'language.english': 'English',
  'language.spanish': 'Español',

  'common.offline': 'Offline',
  'common.today': 'Today',
  'common.yesterday': 'Yesterday',
  'common.cancel': 'Cancel',
  'common.delete': 'Delete',
  'common.all': 'All',
  'common.continue': 'Continue',
  'common.done': 'Done',

  'onboarding.step': 'Step {current} of {total}',
  'onboarding.welcome.title': "Scripture for what you're going through.",
  'onboarding.welcome.subtitle': 'Take a few moments to make Faith & Me yours.',
  'onboarding.welcome.start': 'Get Started',
  'onboarding.welcome.helper': 'You can change these choices later.',
  'onboarding.goals.title': 'What brings you here?',
  'onboarding.goals.subtitle': 'Choose everything that feels true for you.',
  'onboarding.goal.closer': 'Grow closer to God',
  'onboarding.goal.understand': 'Understand the Bible',
  'onboarding.goal.habit': 'Build a daily habit',
  'onboarding.goal.guidance': 'Find guidance',
  'onboarding.goal.pray': 'Pray more',
  'onboarding.goal.peace': 'Find peace',
  'onboarding.goal.difficult': 'Get through something difficult',
  'onboarding.situation.title': 'What are you going through?',
  'onboarding.situation.subtitle': 'You can choose more than one.',
  'onboarding.situation.marriage': 'Marriage',
  'onboarding.situation.temptation': 'Temptation',
  'onboarding.situation.anger': 'Anger',
  'onboarding.situation.grief': 'Grief',
  'onboarding.situation.loneliness': 'Loneliness',
  'onboarding.situation.stress': 'Stress',
  'onboarding.situation.discipline': 'Discipline',
  'onboarding.situation.finances': 'Finances',
  'onboarding.situation.parenting': 'Parenting',
  'onboarding.situation.none': 'Nothing specific right now',
  'onboarding.feeling.title': 'How are you feeling today?',
  'onboarding.feeling.subtitle': 'This helps personalize what you see today.',
  'onboarding.feeling.peaceful': 'Peaceful',
  'onboarding.feeling.grateful': 'Grateful',
  'onboarding.feeling.hopeful': 'Hopeful',
  'onboarding.feeling.anxious': 'Anxious',
  'onboarding.feeling.low': 'Low',
  'onboarding.feeling.frustrated': 'Frustrated',
  'onboarding.feeling.lonely': 'Lonely',
  'onboarding.feeling.lost': 'Lost',
  'onboarding.feeling.skip': 'Prefer not to say',
  'onboarding.reminder.title': 'When would you like a moment with God?',
  'onboarding.reminder.morning': 'Morning',
  'onboarding.reminder.afternoon': 'Afternoon',
  'onboarding.reminder.evening': 'Evening',
  'onboarding.reminder.later': "I'll decide later",
  'onboarding.preview.title': 'Keep His Word close.',
  'onboarding.preview.subtitle': 'Your daily Scripture can meet you right where you already are.',
  'onboarding.preview.verse': '“Be still, and know that I am God.”',
  'onboarding.preview.reference': 'Psalm 46:10',
  'onboarding.preview.free': 'One daily Scripture widget will always be free.',
  'onboarding.ready.title': 'Faith & Me is ready for you.',
  'onboarding.ready.summary.anxiety': "We'll help you make space for peace, Scripture, and reflection each day.",
  'onboarding.ready.summary.purpose': "We'll help you make space for guidance, Scripture, and intentional reflection.",
  'onboarding.ready.summary.peace': "We'll help you make space for peace, Scripture, and steady hope.",
  'onboarding.ready.summary.default': "We'll help you make space for Scripture, prayer, and reflection each day.",
  'onboarding.ready.focus': 'Your Focus',
  'onboarding.ready.start': 'Start my journey',

  'moment.close': 'Close',
  'moment.closeLabel': 'Close session',
  'moment.scriptureUnavailable': 'Scripture is unavailable.',
  'moment.thinkHint': "Take a moment. You don't have to write anything down.",
  'moment.prayHint': 'Read slowly, or make these words your own.',
  'moment.actionHeading': 'One small step.',
  'moment.completeTitle': 'Moment complete.',
  'moment.completeBody': 'Five minutes. One moment to carry with you.',
  'moment.todaysScripture': "Today's Scripture",
  'moment.completeToday': "Complete today's moment",

  'topics.peace': 'Peace',
  'topics.strength': 'Strength',
  'topics.guidance': 'Guidance',
  'topics.love': 'Love',
  'topics.hope': 'Hope',
  'topics.forgiveness': 'Forgiveness',
  'topics.courage': 'Courage',
  'topics.faith': 'Faith',
  'topics.patience': 'Patience',
  'topics.anxiety': 'Anxiety',
  'topics.relationships': 'Relationships',
  'topics.purpose': 'Purpose',
  'topics.money': 'Money',

  'today.feeling': 'Feeling {feeling}',
  'today.greeting': 'Good morning.',
  'today.title': 'What do you need\ntoday?',
  'today.dailyScripture': 'Daily Scripture',
  'today.scriptureUnavailable': 'Scripture is unavailable.',
  'today.sessionTitle': 'Your 5 Minutes With God',
  'today.progressCount': '{completed} of {total}',
  'today.step.scripture': 'Scripture',
  'today.step.reflect': 'Reflect',
  'today.step.think': 'Think',
  'today.step.pray': 'Pray',
  'today.step.act': 'Act',
  'today.dailyStreak': 'Daily streak',
  'today.streak.one': '{count} day streak',
  'today.streak.other': '{count} days streak',
  'today.cta.complete': 'Completed today',
  'today.cta.continue': 'Continue session',
  'today.cta.start': "Start today's moment",

  'ask.title': 'Ask Scripture',
  'ask.heart': "What's on your heart?",
  'ask.subtitle': "Ask about Scripture, faith, or something you're going through.",
  'ask.usage.one': '{count} question available today',
  'ask.usage.other': '{count} questions available today',
  'ask.usage.offline': 'Ask Scripture usage will update when connected.',
  'ask.exhaustedTitle': "You've used today's free questions.",
  'ask.exhaustedBody': 'Come back tomorrow for more.',
  'ask.viewUpgrade': 'View upgrade',
  'ask.placeholder': "I'm struggling with...",
  'ask.inputLabel': 'Ask Scripture question',
  'ask.sendLabel': 'Send question',
  'ask.peopleAsk': 'People often ask',
  'ask.tryAgain': 'Try again',
  'ask.readBible': 'Read the Bible',
  'ask.todaysMoment': "Today's Moment",
  'ask.loading.finding': 'Finding relevant Scripture...',
  'ask.loading.reflecting': 'Reflecting on these passages...',
  'ask.error.dailyTitle': "That's all for today.",
  'ask.error.dailyBody': "You've used today's free Ask Scripture questions. Come back tomorrow for more.",
  'ask.error.setupTitle': 'Ask Scripture needs setup.',
  'ask.error.setupBody': 'Ask Scripture needs a Faith & Me API connection before it can respond.',
  'ask.error.networkTitle': "Couldn't connect right now.",
  'ask.error.networkBody': "Check your connection and try again. You can still read the Bible or continue today's moment offline.",
  'ask.error.breakTitle': 'Ask Scripture is taking a break.',
  'ask.error.breakBody': 'Your Bible, daily Scripture, and 5 Minutes With God are still available.',
  'ask.error.inProgressTitle': 'Still preparing your answer.',
  'ask.error.inProgressBody': 'Your previous question is still being prepared.',
  'ask.error.unknownTitle': 'Try that again?',
  'ask.error.unknownBody': 'Something went wrong while preparing your response.',
  'ask.youAsked': 'You asked',
  'ask.safety': 'Safety',
  'ask.scripture': 'Scripture',
  'ask.whyMatters': 'Why this matters',
  'ask.context': 'Context',
  'ask.meaning': 'What This Could Mean For You',
  'ask.reflect': 'Reflect',
  'ask.prayer': 'Prayer',
  'ask.prayerIntro': "If it's helpful, you might pray:",
  'ask.nextStep': 'One Small Step',
  'ask.followUp': 'Follow up',
  'ask.followUpBody': 'Use this answer as a starting point for a deeper question.',
  'ask.followUp.deep': 'Go deeper',
  'ask.followUp.context': 'Explain context',
  'ask.followUp.prayer': 'Turn into prayer',
  'ask.followUp.plan': '3-day plan',
  'ask.saveTitle': 'Ask Scripture Reflection',
  'ask.saveQuestion': 'Question',
  'ask.saveScripture': 'Scripture',
  'ask.saveContext': 'Context',
  'ask.saveApplication': 'Application',
  'ask.saveReflect': 'Reflect',
  'ask.savePrayer': 'Prayer',
  'ask.saveNextStep': 'Next step',
  'ask.saved': 'Saved to Journal',
  'ask.saving': 'Saving...',
  'ask.save': 'Save to Journal',
  'ask.openJournal': 'Open Journal',
  'ask.askElse': 'Ask something else',
  'ask.suggest.anxiety': "I'm anxious about something I can't control.",
  'ask.suggest.forgiveness': "I'm angry with someone and don't know how to let it go.",
  'ask.suggest.relationships': 'My relationship has been difficult lately.',
  'ask.suggest.purpose': "I don't know what direction to take in life.",
  'ask.suggest.money': "I'm worried about money and how to handle it faithfully.",
  'ask.suggest.faith': "I'm struggling to trust God right now.",
  'ask.followPrompt.deep': 'Go deeper on this answer to my question: "{question}". Help me understand what I may be missing and how to sit with this Scripture.',
  'ask.followPrompt.context': 'Explain the biblical context behind these passages from my question: "{question}". Keep it pastoral and easy to understand.',
  'ask.followPrompt.prayer': 'Turn this answer into a personal prayer for me: "{question}".',
  'ask.followPrompt.plan': 'Give me a simple 3-day Scripture reflection plan based on this question: "{question}".',

  'journal.title': 'Private reflection.',
  'journal.subtitle': 'Prayer, gratitude, and the thoughts you want to keep with God.',
  'journal.kind.prayer': 'Prayer',
  'journal.kind.reflection': 'Reflection',
  'journal.kind.gratitude': 'Gratitude',
  'journal.kindLabel.prayer': 'PRAYER',
  'journal.kindLabel.reflection': 'REFLECTION',
  'journal.kindLabel.gratitude': 'GRATITUDE',
  'journal.prompt.prayer': 'Lord,',
  'journal.prompt.reflection': 'Today I noticed...',
  'journal.prompt.gratitude': 'I am thankful for...',
  'journal.guided': 'Guided prompts',
  'journal.prompt.surrender': 'Surrender',
  'journal.prompt.surrenderText': 'Lord, today I need to surrender...',
  'journal.prompt.intercession': 'Intercession',
  'journal.prompt.intercessionText': 'Lord, I want to pray for...',
  'journal.prompt.courage': 'Courage',
  'journal.prompt.courageText': 'Lord, give me courage to...',
  'journal.prompt.noticed': 'What I noticed',
  'journal.prompt.noticedText': 'Today I noticed God meeting me in...',
  'journal.prompt.heavy': 'What felt heavy',
  'journal.prompt.heavyText': 'Something that felt heavy today was...',
  'journal.prompt.practice': 'What to practice',
  'journal.prompt.practiceText': 'One faithful thing I can practice next is...',
  'journal.prompt.mercy': 'Small mercy',
  'journal.prompt.mercyText': 'A small mercy I received today was...',
  'journal.prompt.person': 'Person',
  'journal.prompt.personText': 'I am thankful for this person because...',
  'journal.prompt.provision': 'Provision',
  'journal.prompt.provisionText': 'God provided for me today through...',
  'journal.characters': '{count} characters',
  'journal.entryLabel': 'Journal entry',
  'journal.saving': 'Saving...',
  'journal.save': 'Save entry',
  'journal.search': 'Search journal',
  'journal.searchLabel': 'Search journal',
  'journal.clearSearch': 'Clear journal search',
  'journal.filter.prayer': 'Prayer',
  'journal.filter.reflection': 'Reflection',
  'journal.filter.gratitude': 'Gratitude',
  'journal.filter.ask': 'From Ask',
  'journal.recent': 'Recent entries',
  'journal.shown': '{filtered}/{total} shown',
  'journal.emptyTitle': 'A quiet place to begin.',
  'journal.emptyBody': 'Your prayers and reflections will stay on this device.',
  'journal.noMatchTitle': 'Nothing matched.',
  'journal.noMatchBody': 'Try a different word or filter.',
  'journal.fromAsk': 'From Ask Scripture',
  'journal.openEntry': 'Open journal entry',
  'journal.deleteEntryLabel': 'Delete journal entry',
  'journal.showMore': 'Show {count} more',
  'journal.deleteTitle': 'Delete entry?',
  'journal.deleteBody': 'This journal entry will be removed from this device.',
  'journal.closeEntry': 'Close journal entry',
  'journal.deleteEntry': 'Delete entry',

  'bible.label': 'Bible',
  'bible.title': 'Berean Standard Bible',
  'bible.attributionShort': 'Berean Standard Bible · BSB',
  'bible.continueReading': 'Continue Reading',
  'bible.chapter': 'Chapter {chapter}',
  'bible.continue': 'Continue',
  'bible.start': 'Open a chapter to begin reading.',
  'bible.chaptersRead': 'Chapters Read',
  'bible.bookmarks': 'Bookmarks',
  'bible.highlights': 'Highlights',
  'bible.savedHighlights': 'Saved & Highlights',
  'bible.oldTestament': 'Old Testament',
  'bible.newTestament': 'New Testament',
  'bible.sourceNote': '{translation} ({abbreviation}) is public domain and bundled for offline reading.',
  'bible.bookUnavailable': 'Book unavailable.',
  'bible.chapterProgress': '{completed} of {total} chapters read.',
  'bible.currentChapter': 'Current chapter',
  'bible.read': 'Read',
  'bible.open': 'Open',
  'bible.chapterUnavailable': 'Chapter unavailable.',
  'bible.backToBookChapters': 'Back to {book} chapters',
  'bible.backToChapters': 'Back to chapters',
  'bible.chapterProgressNoPeriod': '{completed} of {total} chapters read',
  'bible.highlighted': '{count} highlighted',
  'bible.bookmarked': '{count} bookmarked',
  'bible.unhighlight': 'Unhighlight',
  'bible.highlight': 'Highlight',
  'bible.unsave': 'Unsave',
  'bible.bookmark': 'Bookmark',
  'bible.bookmarkedLabel': 'Bookmarked',
  'bible.chapterMarked': 'Chapter marked read',
  'bible.markChapter': 'Mark chapter read',
  'bible.previousChapter': 'Previous Chapter',
  'bible.nextChapter': 'Next Chapter',
  'bible.about': '{translation} ({abbreviation}). Public domain and bundled for offline reading.',
  'savedBible.label': 'Bible Library',
  'savedBible.title': 'Saved Scripture',
  'savedBible.subtitle': 'Keep verses close while you read. Everything here stays on this device.',
  'savedBible.back': 'Back to Bible',
  'savedBible.search': 'Search saved Scripture',
  'savedBible.searchLabel': 'Search saved Scripture',
  'savedBible.clearSearch': 'Clear saved Scripture search',
  'savedBible.all': 'All',
  'savedBible.bookmarkLabel': 'BOOKMARK',
  'savedBible.highlightLabel': 'HIGHLIGHT',
  'savedBible.openChapter': 'Open chapter',
  'savedBible.noSavedTitle': 'No saved Scripture yet.',
  'savedBible.noSavedBody': 'Open a chapter, tap a verse, then save or highlight it here.',
  'savedBible.browse': 'Browse Bible',

  'weekly.close': 'Close weekly review',
  'weekly.label': 'Weekly Review',
  'weekly.title': 'What you carried this week.',
  'weekly.subtitle': 'A local summary of what you prayed, saved, highlighted, and brought into reflection.',
  'weekly.stat.journal': 'journal',
  'weekly.stat.askSaved': 'Ask saved',
  'weekly.stat.scripture': 'Scripture',
  'weekly.theme': 'Theme to notice: {theme}',
  'weekly.themeBody': 'Look for how this theme showed up in your prayers, Scripture, and next steps.',
  'weekly.journalRhythm': 'Journal rhythm',
  'weekly.scriptureRevisit': 'Scripture to revisit',
  'weekly.scriptureEmpty': 'Save or highlight Scripture this week and it will appear here.',
  'weekly.readingProgress': 'Reading progress',
  'weekly.chaptersMarked': '{count} chapters marked read',
  'weekly.chaptersNote': 'Chapter completion is currently tracked as an all-time local count.',
  'weekly.openJournal': 'Open Journal',
  'weekly.savedScripture': 'Saved Scripture',
  'weekly.theme.peace': 'peace',
  'weekly.theme.trust': 'trust',
  'weekly.theme.forgiveness': 'forgiveness',
  'weekly.theme.gratitude': 'gratitude',
  'weekly.theme.purpose': 'purpose',
  'weekly.theme.faithfulness': 'faithfulness',

  'me.label': 'Me',
  'me.title': 'Your walk.',
  'me.subtitle': "A quick view of what you've been reading, saving, and bringing into prayer.",
  'me.journey': 'Your Journey',
  'me.journey.with': 'with',
  'me.open': 'Open',
  'me.stat.streak': 'streak',
  'me.stat.best': 'best {count}',
  'me.stat.today': 'today',
  'me.stat.complete': 'complete',
  'me.stat.inProgress': 'in progress',
  'me.stat.ask': 'Ask',
  'me.stat.dailyLimit': 'daily limit',
  'me.usage.left': '{remaining}/{limit} left',
  'me.shortcuts': 'Shortcuts',
  'me.todayMoment': "Today's moment",
  'me.todayCompleted': 'Completed for today',
  'me.todaySteps': '{completed} of {total} steps complete',
  'me.continueReading': 'Continue reading',
  'me.startReading': 'Start reading',
  'me.openJournal': 'Open Journal',
  'me.entriesSaved.one': '{count} entry saved',
  'me.entriesSaved.other': '{count} entries saved',
  'me.askScripture': 'Ask Scripture',
  'me.usageWhenConnected': 'Usage updates when connected',
  'me.weeklyReview': 'Weekly review',
  'me.weeklyReviewSubtitle': 'Review what you prayed, saved, and noticed',
  'me.upgradeTitle': 'Upgrade to Plus',
  'me.upgradeSubtitle': 'More Ask Scripture and deeper reflection tools',
  'me.library': 'Library',
  'me.chaptersRead': 'chapters read',
  'me.savedVerses': 'saved verses',
  'me.highlights': 'highlights',
  'me.openSavedScripture': 'Open saved Scripture',
  'me.journalSection': 'Journal',
  'me.prayers': 'prayers',
  'me.reflections': 'reflections',
  'me.gratitude': 'gratitude',
  'me.savedFromAsk': '{count} saved from Ask Scripture',
  'me.preferences': 'Preferences',
  'me.language': 'Language',
  'me.bibleTranslation': 'Bible translation',
  'me.bibleTranslationValue': 'Berean Standard Bible (BSB)',
  'me.dailyReminder': 'Daily reminder',
  'me.appearance': 'Appearance',
  'me.appearanceSystem': 'System',
  'me.plusTitle': 'Faith & Me Plus',
  'me.plusHeading': 'More room to ask, reflect, and grow.',
  'me.plusBody': 'Plus will unlock a higher Ask Scripture limit and richer reflection tools once subscriptions are wired.',
  'me.viewUpgrade': 'View upgrade',
  'me.developer': 'Developer',
  'me.developerBody': 'Clear onboarding state and reset the local daily moment state.',
  'me.resetOnboarding': 'Reset onboarding',
  'me.resetToday': "Reset today's moment",
  'me.resetStreak': 'Reset streak',

  'upgrade.close': 'Close upgrade',
  'upgrade.label': 'Faith & Me Plus',
  'upgrade.title': 'More Ask Scripture + guided reflection tools.',
  'upgrade.subtitle': 'Plus is for depth, continuity, and convenience. The essentials stay free.',
  'upgrade.planName': 'Plus',
  'upgrade.plannedSubscription': 'Planned subscription',
  'upgrade.price': '$4.99/mo',
  'upgrade.feature.ask.title': 'More Ask Scripture each day',
  'upgrade.feature.ask.body': 'A higher daily limit with room for follow-up questions like go deeper, context, prayer, and a 3-day plan.',
  'upgrade.feature.journal.title': 'Guided reflection tools',
  'upgrade.feature.journal.body': 'Journal prompts, search, filters, and saved Ask answers that help you return to what God has been showing you.',
  'upgrade.feature.paths.title': 'Weekly review and paths',
  'upgrade.feature.paths.body': 'Spiritual reviews and devotional paths for themes like anxiety, forgiveness, purpose, grief, and trust.',
  'upgrade.alwaysFree': 'Always free',
  'upgrade.free.bible': 'Full Bible access',
  'upgrade.free.daily': 'Daily 5 Minutes With God',
  'upgrade.free.journal': 'Basic Journal',
  'upgrade.free.saved': 'Saved Scripture and highlights',
  'upgrade.free.safety': 'Safety support',
  'upgrade.start': 'Start upgrade',
  'upgrade.restore': 'Restore purchase',
  'upgrade.disclaimer': 'Purchase handling is not active yet. This screen is ready for RevenueCat/App Store subscription wiring.',
  'upgrade.alert.title': 'Subscription setup coming next',
  'upgrade.alert.body': 'The upgrade path is visible now. App Store subscription products and purchase handling still need to be wired before release.',
} as const;

const es: Record<TranslationKey, string> = {
  'tabs.today': 'Hoy',
  'tabs.bible': 'Biblia',
  'tabs.ask': 'Preguntar',
  'tabs.journal': 'Diario',
  'tabs.me': 'Yo',

  'language.english': 'English',
  'language.spanish': 'Español',

  'common.offline': 'Sin conexión',
  'common.today': 'Hoy',
  'common.yesterday': 'Ayer',
  'common.cancel': 'Cancelar',
  'common.delete': 'Eliminar',
  'common.all': 'Todo',
  'common.continue': 'Continuar',
  'common.done': 'Listo',

  'onboarding.step': 'Paso {current} de {total}',
  'onboarding.welcome.title': 'Biblia para lo que estás viviendo.',
  'onboarding.welcome.subtitle': 'Toma unos momentos para hacer Faith & Me tuyo.',
  'onboarding.welcome.start': 'Comenzar',
  'onboarding.welcome.helper': 'Puedes cambiar estas opciones después.',
  'onboarding.goals.title': '¿Qué te trae aquí?',
  'onboarding.goals.subtitle': 'Elige todo lo que se sienta verdadero para ti.',
  'onboarding.goal.closer': 'Acercarme más a Dios',
  'onboarding.goal.understand': 'Entender la Biblia',
  'onboarding.goal.habit': 'Crear un hábito diario',
  'onboarding.goal.guidance': 'Encontrar dirección',
  'onboarding.goal.pray': 'Orar más',
  'onboarding.goal.peace': 'Encontrar paz',
  'onboarding.goal.difficult': 'Atravesar algo difícil',
  'onboarding.situation.title': '¿Qué estás viviendo?',
  'onboarding.situation.subtitle': 'Puedes elegir más de una opción.',
  'onboarding.situation.marriage': 'Matrimonio',
  'onboarding.situation.temptation': 'Tentación',
  'onboarding.situation.anger': 'Enojo',
  'onboarding.situation.grief': 'Duelo',
  'onboarding.situation.loneliness': 'Soledad',
  'onboarding.situation.stress': 'Estrés',
  'onboarding.situation.discipline': 'Disciplina',
  'onboarding.situation.finances': 'Finanzas',
  'onboarding.situation.parenting': 'Crianza',
  'onboarding.situation.none': 'Nada específico ahora',
  'onboarding.feeling.title': '¿Cómo te sientes hoy?',
  'onboarding.feeling.subtitle': 'Esto ayuda a personalizar lo que ves hoy.',
  'onboarding.feeling.peaceful': 'En paz',
  'onboarding.feeling.grateful': 'Agradecido',
  'onboarding.feeling.hopeful': 'Con esperanza',
  'onboarding.feeling.anxious': 'Ansioso',
  'onboarding.feeling.low': 'Bajo de ánimo',
  'onboarding.feeling.frustrated': 'Frustrado',
  'onboarding.feeling.lonely': 'Solo',
  'onboarding.feeling.lost': 'Perdido',
  'onboarding.feeling.skip': 'Prefiero no decir',
  'onboarding.reminder.title': '¿Cuándo quieres un momento con Dios?',
  'onboarding.reminder.morning': 'Mañana',
  'onboarding.reminder.afternoon': 'Tarde',
  'onboarding.reminder.evening': 'Noche',
  'onboarding.reminder.later': 'Lo decidiré después',
  'onboarding.preview.title': 'Mantén Su Palabra cerca.',
  'onboarding.preview.subtitle': 'Tu Biblia diaria puede encontrarte justo donde ya estás.',
  'onboarding.preview.verse': '“Estad quietos, y conoced que yo soy Dios.”',
  'onboarding.preview.reference': 'Salmo 46:10',
  'onboarding.preview.free': 'Un widget diario de Biblia siempre será gratis.',
  'onboarding.ready.title': 'Faith & Me está listo para ti.',
  'onboarding.ready.summary.anxiety': 'Te ayudaremos a crear espacio para paz, Biblia y reflexión cada día.',
  'onboarding.ready.summary.purpose': 'Te ayudaremos a crear espacio para dirección, Biblia y reflexión intencional.',
  'onboarding.ready.summary.peace': 'Te ayudaremos a crear espacio para paz, Biblia y esperanza constante.',
  'onboarding.ready.summary.default': 'Te ayudaremos a crear espacio para Biblia, oración y reflexión cada día.',
  'onboarding.ready.focus': 'Tu enfoque',
  'onboarding.ready.start': 'Empezar mi camino',

  'moment.close': 'Cerrar',
  'moment.closeLabel': 'Cerrar sesión',
  'moment.scriptureUnavailable': 'La lectura no está disponible.',
  'moment.thinkHint': 'Toma un momento. No tienes que escribir nada.',
  'moment.prayHint': 'Lee despacio, o haz tuyas estas palabras.',
  'moment.actionHeading': 'Un paso pequeño.',
  'moment.completeTitle': 'Momento completo.',
  'moment.completeBody': 'Cinco minutos. Un momento para llevar contigo.',
  'moment.todaysScripture': 'Biblia de hoy',
  'moment.completeToday': 'Completar momento de hoy',

  'topics.peace': 'Paz',
  'topics.strength': 'Fortaleza',
  'topics.guidance': 'Dirección',
  'topics.love': 'Amor',
  'topics.hope': 'Esperanza',
  'topics.forgiveness': 'Perdón',
  'topics.courage': 'Valentía',
  'topics.faith': 'Fe',
  'topics.patience': 'Paciencia',
  'topics.anxiety': 'Ansiedad',
  'topics.relationships': 'Relaciones',
  'topics.purpose': 'Propósito',
  'topics.money': 'Dinero',

  'today.feeling': 'Sintiendo {feeling}',
  'today.greeting': 'Buenos días.',
  'today.title': '¿Qué necesitas\nhoy?',
  'today.dailyScripture': 'Biblia diaria',
  'today.scriptureUnavailable': 'La lectura no está disponible.',
  'today.sessionTitle': 'Tus 5 minutos con Dios',
  'today.progressCount': '{completed} de {total}',
  'today.step.scripture': 'Biblia',
  'today.step.reflect': 'Reflexiona',
  'today.step.think': 'Piensa',
  'today.step.pray': 'Ora',
  'today.step.act': 'Actúa',
  'today.dailyStreak': 'Racha diaria',
  'today.streak.one': 'racha de {count} día',
  'today.streak.other': 'racha de {count} días',
  'today.cta.complete': 'Completado hoy',
  'today.cta.continue': 'Continuar sesión',
  'today.cta.start': 'Empezar momento de hoy',

  'ask.title': 'Preguntar a la Biblia',
  'ask.heart': '¿Qué llevas en el corazón?',
  'ask.subtitle': 'Pregunta sobre la Biblia, la fe o algo que estás viviendo.',
  'ask.usage.one': '{count} pregunta disponible hoy',
  'ask.usage.other': '{count} preguntas disponibles hoy',
  'ask.usage.offline': 'El uso de Preguntar se actualizará al conectarse.',
  'ask.exhaustedTitle': 'Usaste tus preguntas gratis de hoy.',
  'ask.exhaustedBody': 'Vuelve mañana para más.',
  'ask.viewUpgrade': 'Ver mejora',
  'ask.placeholder': 'Estoy luchando con...',
  'ask.inputLabel': 'Pregunta para la Biblia',
  'ask.sendLabel': 'Enviar pregunta',
  'ask.peopleAsk': 'La gente suele preguntar',
  'ask.tryAgain': 'Intentar de nuevo',
  'ask.readBible': 'Leer la Biblia',
  'ask.todaysMoment': 'Momento de hoy',
  'ask.loading.finding': 'Buscando pasajes relevantes...',
  'ask.loading.reflecting': 'Reflexionando sobre estos pasajes...',
  'ask.error.dailyTitle': 'Eso es todo por hoy.',
  'ask.error.dailyBody': 'Ya usaste tus preguntas gratis de Preguntar por hoy. Vuelve mañana para más.',
  'ask.error.setupTitle': 'Preguntar necesita configuración.',
  'ask.error.setupBody': 'Preguntar necesita una conexión a la API de Faith & Me antes de responder.',
  'ask.error.networkTitle': 'No se pudo conectar ahora.',
  'ask.error.networkBody': 'Revisa tu conexión e inténtalo de nuevo. Todavía puedes leer la Biblia o continuar el momento de hoy sin conexión.',
  'ask.error.breakTitle': 'Preguntar está tomando un descanso.',
  'ask.error.breakBody': 'Tu Biblia, la lectura diaria y 5 minutos con Dios siguen disponibles.',
  'ask.error.inProgressTitle': 'Aún estamos preparando tu respuesta.',
  'ask.error.inProgressBody': 'Tu pregunta anterior todavía se está preparando.',
  'ask.error.unknownTitle': '¿Intentamos otra vez?',
  'ask.error.unknownBody': 'Algo salió mal al preparar tu respuesta.',
  'ask.youAsked': 'Preguntaste',
  'ask.safety': 'Seguridad',
  'ask.scripture': 'Biblia',
  'ask.whyMatters': 'Por qué importa',
  'ask.context': 'Contexto',
  'ask.meaning': 'Qué podría significar para ti',
  'ask.reflect': 'Reflexiona',
  'ask.prayer': 'Oración',
  'ask.prayerIntro': 'Si te ayuda, podrías orar:',
  'ask.nextStep': 'Un paso pequeño',
  'ask.followUp': 'Seguimiento',
  'ask.followUpBody': 'Usa esta respuesta como punto de partida para una pregunta más profunda.',
  'ask.followUp.deep': 'Profundizar',
  'ask.followUp.context': 'Explicar contexto',
  'ask.followUp.prayer': 'Convertir en oración',
  'ask.followUp.plan': 'Plan de 3 días',
  'ask.saveTitle': 'Reflexión de Preguntar',
  'ask.saveQuestion': 'Pregunta',
  'ask.saveScripture': 'Biblia',
  'ask.saveContext': 'Contexto',
  'ask.saveApplication': 'Aplicación',
  'ask.saveReflect': 'Reflexiona',
  'ask.savePrayer': 'Oración',
  'ask.saveNextStep': 'Próximo paso',
  'ask.saved': 'Guardado en Diario',
  'ask.saving': 'Guardando...',
  'ask.save': 'Guardar en Diario',
  'ask.openJournal': 'Abrir Diario',
  'ask.askElse': 'Preguntar otra cosa',
  'ask.suggest.anxiety': 'Estoy ansioso por algo que no puedo controlar.',
  'ask.suggest.forgiveness': 'Estoy enojado con alguien y no sé cómo soltarlo.',
  'ask.suggest.relationships': 'Mi relación ha estado difícil últimamente.',
  'ask.suggest.purpose': 'No sé qué dirección tomar en mi vida.',
  'ask.suggest.money': 'Estoy preocupado por el dinero y por manejarlo con fe.',
  'ask.suggest.faith': 'Estoy luchando por confiar en Dios ahora mismo.',
  'ask.followPrompt.deep': 'Profundiza en esta respuesta a mi pregunta: "{question}". Ayúdame a entender qué podría estar pasando por alto y cómo sentarme con este pasaje.',
  'ask.followPrompt.context': 'Explica el contexto bíblico detrás de estos pasajes de mi pregunta: "{question}". Mantenlo pastoral y fácil de entender.',
  'ask.followPrompt.prayer': 'Convierte esta respuesta en una oración personal para mí: "{question}".',
  'ask.followPrompt.plan': 'Dame un plan sencillo de reflexión bíblica de 3 días basado en esta pregunta: "{question}".',

  'journal.title': 'Reflexión privada.',
  'journal.subtitle': 'Oración, gratitud y los pensamientos que quieres guardar con Dios.',
  'journal.kind.prayer': 'Oración',
  'journal.kind.reflection': 'Reflexión',
  'journal.kind.gratitude': 'Gratitud',
  'journal.kindLabel.prayer': 'ORACIÓN',
  'journal.kindLabel.reflection': 'REFLEXIÓN',
  'journal.kindLabel.gratitude': 'GRATITUD',
  'journal.prompt.prayer': 'Señor,',
  'journal.prompt.reflection': 'Hoy noté...',
  'journal.prompt.gratitude': 'Estoy agradecido por...',
  'journal.guided': 'Prompts guiados',
  'journal.prompt.surrender': 'Rendición',
  'journal.prompt.surrenderText': 'Señor, hoy necesito rendir...',
  'journal.prompt.intercession': 'Intercesión',
  'journal.prompt.intercessionText': 'Señor, quiero orar por...',
  'journal.prompt.courage': 'Valentía',
  'journal.prompt.courageText': 'Señor, dame valentía para...',
  'journal.prompt.noticed': 'Lo que noté',
  'journal.prompt.noticedText': 'Hoy noté a Dios encontrándome en...',
  'journal.prompt.heavy': 'Lo que pesó',
  'journal.prompt.heavyText': 'Algo que se sintió pesado hoy fue...',
  'journal.prompt.practice': 'Qué practicar',
  'journal.prompt.practiceText': 'Una cosa fiel que puedo practicar ahora es...',
  'journal.prompt.mercy': 'Pequeña misericordia',
  'journal.prompt.mercyText': 'Una pequeña misericordia que recibí hoy fue...',
  'journal.prompt.person': 'Persona',
  'journal.prompt.personText': 'Estoy agradecido por esta persona porque...',
  'journal.prompt.provision': 'Provisión',
  'journal.prompt.provisionText': 'Dios proveyó para mí hoy por medio de...',
  'journal.characters': '{count} caracteres',
  'journal.entryLabel': 'Entrada del diario',
  'journal.saving': 'Guardando...',
  'journal.save': 'Guardar entrada',
  'journal.search': 'Buscar en diario',
  'journal.searchLabel': 'Buscar en diario',
  'journal.clearSearch': 'Limpiar búsqueda del diario',
  'journal.filter.prayer': 'Oración',
  'journal.filter.reflection': 'Reflexión',
  'journal.filter.gratitude': 'Gratitud',
  'journal.filter.ask': 'Desde Preguntar',
  'journal.recent': 'Entradas recientes',
  'journal.shown': '{filtered}/{total} visibles',
  'journal.emptyTitle': 'Un lugar tranquilo para empezar.',
  'journal.emptyBody': 'Tus oraciones y reflexiones se quedarán en este dispositivo.',
  'journal.noMatchTitle': 'Nada coincidió.',
  'journal.noMatchBody': 'Prueba otra palabra o filtro.',
  'journal.fromAsk': 'Desde Preguntar',
  'journal.openEntry': 'Abrir entrada del diario',
  'journal.deleteEntryLabel': 'Eliminar entrada del diario',
  'journal.showMore': 'Mostrar {count} más',
  'journal.deleteTitle': '¿Eliminar entrada?',
  'journal.deleteBody': 'Esta entrada del diario se eliminará de este dispositivo.',
  'journal.closeEntry': 'Cerrar entrada del diario',
  'journal.deleteEntry': 'Eliminar entrada',

  'bible.label': 'Biblia',
  'bible.title': 'Berean Standard Bible',
  'bible.attributionShort': 'Berean Standard Bible · BSB',
  'bible.continueReading': 'Seguir leyendo',
  'bible.chapter': 'Capítulo {chapter}',
  'bible.continue': 'Continuar',
  'bible.start': 'Abre un capítulo para empezar a leer.',
  'bible.chaptersRead': 'Capítulos leídos',
  'bible.bookmarks': 'Guardados',
  'bible.highlights': 'Resaltados',
  'bible.savedHighlights': 'Guardados y resaltados',
  'bible.oldTestament': 'Antiguo Testamento',
  'bible.newTestament': 'Nuevo Testamento',
  'bible.sourceNote': '{translation} ({abbreviation}) es de dominio público y viene incluida para lectura sin conexión.',
  'bible.bookUnavailable': 'Libro no disponible.',
  'bible.chapterProgress': '{completed} de {total} capítulos leídos.',
  'bible.currentChapter': 'Capítulo actual',
  'bible.read': 'Leído',
  'bible.open': 'Abrir',
  'bible.chapterUnavailable': 'Capítulo no disponible.',
  'bible.backToBookChapters': 'Volver a capítulos de {book}',
  'bible.backToChapters': 'Volver a capítulos',
  'bible.chapterProgressNoPeriod': '{completed} de {total} capítulos leídos',
  'bible.highlighted': '{count} resaltados',
  'bible.bookmarked': '{count} guardados',
  'bible.unhighlight': 'Quitar resaltado',
  'bible.highlight': 'Resaltar',
  'bible.unsave': 'Quitar guardado',
  'bible.bookmark': 'Guardar',
  'bible.bookmarkedLabel': 'Guardado',
  'bible.chapterMarked': 'Capítulo marcado como leído',
  'bible.markChapter': 'Marcar capítulo leído',
  'bible.previousChapter': 'Capítulo anterior',
  'bible.nextChapter': 'Capítulo siguiente',
  'bible.about': '{translation} ({abbreviation}). De dominio público e incluida para lectura sin conexión.',
  'savedBible.label': 'Biblioteca bíblica',
  'savedBible.title': 'Biblia guardada',
  'savedBible.subtitle': 'Mantén cerca los versículos mientras lees. Todo aquí se queda en este dispositivo.',
  'savedBible.back': 'Volver a Biblia',
  'savedBible.search': 'Buscar Biblia guardada',
  'savedBible.searchLabel': 'Buscar Biblia guardada',
  'savedBible.clearSearch': 'Limpiar búsqueda de Biblia guardada',
  'savedBible.all': 'Todo',
  'savedBible.bookmarkLabel': 'GUARDADO',
  'savedBible.highlightLabel': 'RESALTADO',
  'savedBible.openChapter': 'Abrir capítulo',
  'savedBible.noSavedTitle': 'Aún no hay Biblia guardada.',
  'savedBible.noSavedBody': 'Abre un capítulo, toca un versículo y luego guárdalo o resáltalo aquí.',
  'savedBible.browse': 'Explorar Biblia',

  'weekly.close': 'Cerrar resumen semanal',
  'weekly.label': 'Resumen semanal',
  'weekly.title': 'Lo que cargaste esta semana.',
  'weekly.subtitle': 'Un resumen local de lo que oraste, guardaste, resaltaste y llevaste a reflexión.',
  'weekly.stat.journal': 'diario',
  'weekly.stat.askSaved': 'Preguntar guardado',
  'weekly.stat.scripture': 'Biblia',
  'weekly.theme': 'Tema para notar: {theme}',
  'weekly.themeBody': 'Busca cómo apareció este tema en tus oraciones, la Biblia y tus próximos pasos.',
  'weekly.journalRhythm': 'Ritmo del diario',
  'weekly.scriptureRevisit': 'Biblia para volver a visitar',
  'weekly.scriptureEmpty': 'Guarda o resalta Biblia esta semana y aparecerá aquí.',
  'weekly.readingProgress': 'Progreso de lectura',
  'weekly.chaptersMarked': '{count} capítulos marcados como leídos',
  'weekly.chaptersNote': 'La finalización de capítulos actualmente se registra como un conteo local total.',
  'weekly.openJournal': 'Abrir Diario',
  'weekly.savedScripture': 'Biblia guardada',
  'weekly.theme.peace': 'paz',
  'weekly.theme.trust': 'confianza',
  'weekly.theme.forgiveness': 'perdón',
  'weekly.theme.gratitude': 'gratitud',
  'weekly.theme.purpose': 'propósito',
  'weekly.theme.faithfulness': 'fidelidad',

  'me.label': 'Yo',
  'me.title': 'Tu caminar.',
  'me.subtitle': 'Un vistazo a lo que has leído, guardado y llevado a la oración.',
  'me.journey': 'Tu jornada',
  'me.journey.with': 'con',
  'me.open': 'Abierto',
  'me.stat.streak': 'racha',
  'me.stat.best': 'mejor {count}',
  'me.stat.today': 'hoy',
  'me.stat.complete': 'completo',
  'me.stat.inProgress': 'en progreso',
  'me.stat.ask': 'Preguntar',
  'me.stat.dailyLimit': 'límite diario',
  'me.usage.left': 'quedan {remaining}/{limit}',
  'me.shortcuts': 'Accesos',
  'me.todayMoment': 'Momento de hoy',
  'me.todayCompleted': 'Completado por hoy',
  'me.todaySteps': '{completed} de {total} pasos completos',
  'me.continueReading': 'Seguir leyendo',
  'me.startReading': 'Empezar a leer',
  'me.openJournal': 'Abrir diario',
  'me.entriesSaved.one': '{count} entrada guardada',
  'me.entriesSaved.other': '{count} entradas guardadas',
  'me.askScripture': 'Preguntar a la Biblia',
  'me.usageWhenConnected': 'El uso se actualiza al conectarse',
  'me.weeklyReview': 'Resumen semanal',
  'me.weeklyReviewSubtitle': 'Revisa lo que oraste, guardaste y notaste',
  'me.upgradeTitle': 'Mejorar a Plus',
  'me.upgradeSubtitle': 'Más Preguntar y herramientas de reflexión',
  'me.library': 'Biblioteca',
  'me.chaptersRead': 'capítulos leídos',
  'me.savedVerses': 'versículos guardados',
  'me.highlights': 'resaltados',
  'me.openSavedScripture': 'Abrir Biblia guardada',
  'me.journalSection': 'Diario',
  'me.prayers': 'oraciones',
  'me.reflections': 'reflexiones',
  'me.gratitude': 'gratitud',
  'me.savedFromAsk': '{count} guardados desde Preguntar',
  'me.preferences': 'Preferencias',
  'me.language': 'Idioma',
  'me.bibleTranslation': 'Traducción bíblica',
  'me.bibleTranslationValue': 'Berean Standard Bible (BSB)',
  'me.dailyReminder': 'Recordatorio diario',
  'me.appearance': 'Apariencia',
  'me.appearanceSystem': 'Sistema',
  'me.plusTitle': 'Faith & Me Plus',
  'me.plusHeading': 'Más espacio para preguntar, reflexionar y crecer.',
  'me.plusBody': 'Plus desbloqueará un límite más alto para Preguntar y herramientas de reflexión más profundas cuando conectemos las suscripciones.',
  'me.viewUpgrade': 'Ver mejora',
  'me.developer': 'Desarrollador',
  'me.developerBody': 'Borra el onboarding y reinicia el estado local del momento diario.',
  'me.resetOnboarding': 'Reiniciar onboarding',
  'me.resetToday': 'Reiniciar momento de hoy',
  'me.resetStreak': 'Reiniciar racha',

  'upgrade.close': 'Cerrar mejora',
  'upgrade.label': 'Faith & Me Plus',
  'upgrade.title': 'Más Preguntar + herramientas de reflexión guiada.',
  'upgrade.subtitle': 'Plus es para profundidad, continuidad y conveniencia. Lo esencial sigue gratis.',
  'upgrade.planName': 'Plus',
  'upgrade.plannedSubscription': 'Suscripción planificada',
  'upgrade.price': '$4.99/mes',
  'upgrade.feature.ask.title': 'Más Preguntar cada día',
  'upgrade.feature.ask.body': 'Un límite diario más alto, con espacio para preguntas de seguimiento como profundizar, contexto, oración y un plan de 3 días.',
  'upgrade.feature.journal.title': 'Herramientas de reflexión guiada',
  'upgrade.feature.journal.body': 'Prompts para el diario, búsqueda, filtros y respuestas guardadas que te ayudan a volver a lo que Dios te ha estado mostrando.',
  'upgrade.feature.paths.title': 'Resumen semanal y caminos',
  'upgrade.feature.paths.body': 'Resúmenes espirituales y caminos devocionales para temas como ansiedad, perdón, propósito, duelo y confianza.',
  'upgrade.alwaysFree': 'Siempre gratis',
  'upgrade.free.bible': 'Acceso completo a la Biblia',
  'upgrade.free.daily': '5 minutos diarios con Dios',
  'upgrade.free.journal': 'Diario básico',
  'upgrade.free.saved': 'Biblia guardada y resaltados',
  'upgrade.free.safety': 'Apoyo de seguridad',
  'upgrade.start': 'Comenzar mejora',
  'upgrade.restore': 'Restaurar compra',
  'upgrade.disclaimer': 'Las compras aún no están activas. Esta pantalla está lista para conectar RevenueCat/App Store.',
  'upgrade.alert.title': 'La suscripción viene después',
  'upgrade.alert.body': 'La ruta de mejora ya está visible. Aún falta conectar productos de suscripción de App Store y el manejo de compras antes del lanzamiento.',
};

export type TranslationKey = keyof typeof en;
type TranslationParams = Record<string, string | number>;

type LanguageContextValue = {
  language: AppLanguage;
  setLanguage: (language: AppLanguage) => Promise<void>;
  t: (key: TranslationKey, params?: TranslationParams) => string;
};

const dictionaries: Record<AppLanguage, Record<TranslationKey, string>> = {
  en,
  es,
};

const LanguageContext = createContext<LanguageContextValue | null>(null);

function interpolate(template: string, params?: TranslationParams) {
  if (!params) return template;

  return Object.entries(params).reduce((text, [key, value]) => {
    return text.split(`{${key}}`).join(String(value));
  }, template);
}

function normalizeLanguage(value: string | null): AppLanguage {
  return value === 'es' ? 'es' : 'en';
}

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<AppLanguage>('en');

  useEffect(() => {
    let active = true;

    void AsyncStorage.getItem(LANGUAGE_STORAGE_KEY).then((storedLanguage) => {
      if (!active) return;
      setLanguageState(normalizeLanguage(storedLanguage));
    });

    return () => {
      active = false;
    };
  }, []);

  const value = useMemo<LanguageContextValue>(() => {
    return {
      language,
      setLanguage: async (nextLanguage) => {
        setLanguageState(nextLanguage);
        await AsyncStorage.setItem(LANGUAGE_STORAGE_KEY, nextLanguage);
      },
      t: (key, params) => {
        const template = dictionaries[language][key] ?? dictionaries.en[key] ?? key;
        return interpolate(template, params);
      },
    };
  }, [language]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);

  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }

  return context;
}
